-- M2-5/M2-7 base: exposure snapshots and immutable change events.

CREATE TABLE exposure (
    id             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id      VARCHAR(64)   NOT NULL DEFAULT '',
    org_id         VARCHAR(64)   NOT NULL DEFAULT '',
    project_id     BIGINT UNSIGNED NOT NULL,
    asset_id       BIGINT UNSIGNED NOT NULL,
    exposure_type  VARCHAR(32)   NOT NULL,
    exposure_key   VARCHAR(512)  NOT NULL,
    name           VARCHAR(255)  NOT NULL DEFAULT '',
    value          VARCHAR(1024) NOT NULL DEFAULT '',
    protocol       VARCHAR(16)   NOT NULL DEFAULT '',
    port           INT UNSIGNED  NOT NULL DEFAULT 0,
    service        VARCHAR(128)  NOT NULL DEFAULT '',
    version        VARCHAR(128)  NOT NULL DEFAULT '',
    cpe            VARCHAR(255)  NOT NULL DEFAULT '',
    url            VARCHAR(1024) NOT NULL DEFAULT '',
    fingerprint    VARCHAR(255)  NOT NULL DEFAULT '',
    cert_subject   VARCHAR(255)  NOT NULL DEFAULT '',
    cert_issuer    VARCHAR(255)  NOT NULL DEFAULT '',
    cert_serial    VARCHAR(128)  NOT NULL DEFAULT '',
    cert_not_before DATETIME(3)  NOT NULL DEFAULT '1970-01-01 00:00:00.000',
    cert_not_after  DATETIME(3)  NOT NULL DEFAULT '1970-01-01 00:00:00.000',
    cert_san_json  JSON          NULL,
    evidence_hash  CHAR(64)      NOT NULL DEFAULT '',
    source         VARCHAR(64)   NOT NULL DEFAULT '',
    confidence     TINYINT UNSIGNED NOT NULL DEFAULT 100,
    first_seen     DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    last_seen      DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_at     DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at     DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    created_by     VARCHAR(64)   NOT NULL DEFAULT '',
    updated_by     VARCHAR(64)   NOT NULL DEFAULT '',
    deleted_at     DATETIME(3)   NOT NULL DEFAULT '1970-01-01 00:00:00.000',
    PRIMARY KEY (id),
    UNIQUE KEY uk_exposure_key (project_id, exposure_key, deleted_at),
    KEY idx_exposure_asset (project_id, asset_id),
    KEY idx_exposure_type (project_id, exposure_type),
    KEY idx_exposure_cpe (project_id, cpe),
    KEY idx_exposure_cert_expiry (project_id, cert_not_after),
    CONSTRAINT fk_exposure_asset FOREIGN KEY (tenant_id, org_id, project_id, asset_id)
        REFERENCES asset (tenant_id, org_id, project_id, id) ON DELETE CASCADE,
    CONSTRAINT chk_exposure_type CHECK (exposure_type IN ('port', 'service', 'web', 'certificate', 'cloud_config')),
    CONSTRAINT chk_exposure_confidence CHECK (confidence <= 100),
    CONSTRAINT chk_exposure_port CHECK (port <= 65535)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE change_event (
    id             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id      VARCHAR(64)   NOT NULL DEFAULT '',
    org_id         VARCHAR(64)   NOT NULL DEFAULT '',
    project_id     BIGINT UNSIGNED NOT NULL,
    entity_type    VARCHAR(32)   NOT NULL,
    entity_id      BIGINT UNSIGNED NOT NULL,
    change_type    VARCHAR(32)   NOT NULL,
    severity       VARCHAR(32)   NOT NULL DEFAULT 'info',
    title          VARCHAR(255)  NOT NULL DEFAULT '',
    summary        VARCHAR(1024) NOT NULL DEFAULT '',
    source         VARCHAR(64)   NOT NULL DEFAULT '',
    before_json    JSON          NULL,
    after_json     JSON          NULL,
    detected_at    DATETIME(3)   NOT NULL,
    created_at     DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id, detected_at),
    KEY idx_change_event_feed (tenant_id, org_id, project_id, detected_at),
    KEY idx_change_event_type (tenant_id, project_id, change_type, detected_at),
    KEY idx_change_event_entity (tenant_id, project_id, entity_type, entity_id, detected_at),
    CONSTRAINT chk_change_event_entity_type CHECK (entity_type IN ('asset', 'exposure', 'certificate', 'risk')),
    CONSTRAINT chk_change_event_change_type CHECK (change_type IN ('new', 'removed', 'reopened', 'modified')),
    CONSTRAINT chk_change_event_severity CHECK (severity IN ('info', 'low', 'medium', 'high', 'critical'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
