-- sqlc schema for discovery task template/run domain.

CREATE TABLE task_template (
    id               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id        VARCHAR(64)    NOT NULL DEFAULT '',
    org_id           VARCHAR(64)    NOT NULL DEFAULT '',
    project_id       BIGINT UNSIGNED NOT NULL,
    scope_id         BIGINT UNSIGNED NOT NULL,
    name             VARCHAR(128)   NOT NULL DEFAULT '',
    task_type        VARCHAR(32)    NOT NULL,
    config           JSON           NOT NULL,
    schedule         VARCHAR(255)   NOT NULL DEFAULT '',
    enabled          TINYINT(1)     NOT NULL DEFAULT 0,
    timeout_seconds  INT            NOT NULL,
    rate_limit       INT            NOT NULL,
    concurrency      INT            NOT NULL,
    retry_limit      INT            NOT NULL,
    created_at       DATETIME(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at       DATETIME(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    created_by       VARCHAR(64)    NOT NULL DEFAULT '',
    updated_by       VARCHAR(64)    NOT NULL DEFAULT '',
    deleted_at       DATETIME(3)    NOT NULL DEFAULT '1970-01-01 00:00:00.000',
    PRIMARY KEY (id),
    UNIQUE KEY uk_task_template_project_id (project_id, id),
    UNIQUE KEY uk_task_template_project_name (project_id, name, deleted_at),
    KEY idx_task_template_project (project_id, enabled, deleted_at),
    CONSTRAINT fk_task_template_scope_scope_project FOREIGN KEY (project_id, scope_id) REFERENCES scope (project_id, id) ON DELETE CASCADE,
    CONSTRAINT chk_task_template_type CHECK (task_type IN ('dns', 'ct_log', 'port_probe', 'web_probe', 'fingerprint', 'cloud_sync', 'passive_intel', 'import')),
    CONSTRAINT chk_task_template_timeout CHECK (timeout_seconds BETWEEN 1 AND 86400),
    CONSTRAINT chk_task_template_rates CHECK (rate_limit BETWEEN 1 AND 10000),
    CONSTRAINT chk_task_template_concurrency CHECK (concurrency BETWEEN 1 AND 500),
    CONSTRAINT chk_task_template_retry CHECK (retry_limit BETWEEN 0 AND 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE task_run (
    id                 BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id          VARCHAR(64)   NOT NULL DEFAULT '',
    org_id             VARCHAR(64)   NOT NULL DEFAULT '',
    project_id         BIGINT UNSIGNED NOT NULL,
    template_id        BIGINT UNSIGNED NOT NULL,
    scope_id           BIGINT UNSIGNED NOT NULL,
    task_type          VARCHAR(32)   NOT NULL,
    status             VARCHAR(16)   NOT NULL,
    progress           INT           NOT NULL DEFAULT 0,
    timeout_seconds    INT           NOT NULL,
    rate_limit         INT           NOT NULL,
    concurrency        INT           NOT NULL,
    retry_limit        INT           NOT NULL,
    attempt            INT           NOT NULL DEFAULT 0,
    engine_job_id      VARCHAR(255)  NOT NULL DEFAULT '',
    dispatched_at      DATETIME(3)   NOT NULL DEFAULT '1970-01-01 00:00:00.000',
    last_callback_at   DATETIME(3)   NOT NULL DEFAULT '1970-01-01 00:00:00.000',
    result_count       BIGINT UNSIGNED NOT NULL DEFAULT 0,
    callback_secret_ref VARCHAR(255)  NOT NULL DEFAULT '',
    started_at         DATETIME(3)   NOT NULL DEFAULT '1970-01-01 00:00:00.000',
    finished_at        DATETIME(3)   NOT NULL DEFAULT '1970-01-01 00:00:00.000',
    error_summary      VARCHAR(1024) NOT NULL DEFAULT '',
    created_at         DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at         DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    created_by         VARCHAR(64)   NOT NULL DEFAULT '',
    updated_by         VARCHAR(64)   NOT NULL DEFAULT '',
    deleted_at         DATETIME(3)   NOT NULL DEFAULT '1970-01-01 00:00:00.000',
    PRIMARY KEY (id),
    UNIQUE KEY uk_task_run_project_id (project_id, id),
    KEY idx_task_run_project (project_id, status, deleted_at),
    KEY idx_task_run_scope (project_id, scope_id),
    CONSTRAINT fk_task_run_template_project FOREIGN KEY (project_id, template_id) REFERENCES task_template (project_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_task_run_scope_project FOREIGN KEY (project_id, scope_id) REFERENCES scope (project_id, id) ON DELETE CASCADE,
    CONSTRAINT chk_task_run_status CHECK (status IN ('pending', 'running', 'success', 'partial_success', 'failed', 'cancelled')),
    CONSTRAINT chk_task_run_progress CHECK (progress BETWEEN 0 AND 100),
    CONSTRAINT chk_task_run_attempt CHECK (attempt >= 0),
    CONSTRAINT chk_task_run_timeout CHECK (timeout_seconds BETWEEN 1 AND 86400),
    CONSTRAINT chk_task_run_rates CHECK (rate_limit BETWEEN 1 AND 10000),
    CONSTRAINT chk_task_run_concurrency CHECK (concurrency BETWEEN 1 AND 500),
    CONSTRAINT chk_task_run_retry CHECK (retry_limit BETWEEN 0 AND 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
