CREATE TABLE IF NOT EXISTS report_export (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id VARCHAR(64) NOT NULL DEFAULT '',
    org_id VARCHAR(64) NOT NULL DEFAULT '',
    project_id BIGINT UNSIGNED NOT NULL,
    report_type VARCHAR(32) NOT NULL,
    status ENUM('pending','running','succeeded','failed','cancelled') NOT NULL DEFAULT 'pending',
    format ENUM('jsonl','csv') NOT NULL DEFAULT 'jsonl',
    fields_json JSON NOT NULL,
    filters_json JSON NOT NULL,
    redacted TINYINT(1) NOT NULL DEFAULT 1,
    row_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    file_path VARCHAR(512) NOT NULL DEFAULT '',
    error_message VARCHAR(512) NOT NULL DEFAULT '',
    requested_by VARCHAR(128) NOT NULL DEFAULT '',
    started_at DATETIME(3) NOT NULL DEFAULT '1970-01-01 00:00:00.000',
    finished_at DATETIME(3) NOT NULL DEFAULT '1970-01-01 00:00:00.000',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at DATETIME(3) NOT NULL DEFAULT '1970-01-01 00:00:00.000',
    PRIMARY KEY (id),
    KEY idx_report_export_project_status (project_id, status, deleted_at, id),
    KEY idx_report_export_project_created (project_id, created_at, deleted_at),
    CONSTRAINT chk_report_export_report_type CHECK (report_type IN ('risk','ticket','exposure'))
);
