export enum Permission {
  UserRead = 'user:read',
  UserWrite = 'user:write',
  UserCredentialReset = 'user:credential:reset',
  UserRoleWrite = 'user:role:write',
  AssetRead = 'asset:read',
  AssetWrite = 'asset:write',
  AssetDelete = 'asset:delete',
  ExposureRead = 'exposure:read',
  ScopeRead = 'scope:read',
  ScopeWrite = 'scope:write',
  DiscoveryRead = 'discovery:read',
  DiscoveryRun = 'discovery:run',
  RiskRead = 'risk:read',
  RiskWrite = 'risk:write',
  RiskAccept = 'risk:accept',
  RiskSuppress = 'risk:suppress',
  TicketRead = 'ticket:read',
  TicketWrite = 'ticket:write',
  TicketApprove = 'ticket:approve',
  ReportRead = 'report:read',
  ReportExport = 'report:export',
  NotificationWrite = 'notification:write',
  AdminManage = 'admin:manage',
  AuditRead = 'audit:read',
  ProjectAccess = 'project:access',
  ProjectRead = 'project:read',
  ProjectCreate = 'project:create',
  ProjectWrite = 'project:write',
  ProjectArchive = 'project:archive',
  ProjectMemberWrite = 'project:member:write'
}

export type Role = 'system_admin' | 'security_admin' | 'project_owner' | 'security_ops' | 'developer' | 'viewer';

export const rolePermissions: Record<Role, Permission[]> = {
  system_admin: [
    Permission.UserRead,
    Permission.UserWrite,
    Permission.UserCredentialReset,
    Permission.UserRoleWrite,
    Permission.AssetRead,
    Permission.AssetWrite,
    Permission.AssetDelete,
    Permission.ExposureRead,
    Permission.ScopeRead,
    Permission.ScopeWrite,
    Permission.DiscoveryRead,
    Permission.DiscoveryRun,
    Permission.RiskRead,
    Permission.RiskWrite,
    Permission.RiskAccept,
    Permission.RiskSuppress,
    Permission.TicketRead,
    Permission.TicketWrite,
    Permission.TicketApprove,
    Permission.ReportRead,
    Permission.ReportExport,
    Permission.NotificationWrite,
    Permission.AdminManage,
    Permission.AuditRead,
    Permission.ProjectAccess,
    Permission.ProjectRead,
    Permission.ProjectCreate,
    Permission.ProjectWrite,
    Permission.ProjectArchive,
    Permission.ProjectMemberWrite
  ],
  security_admin: [
    Permission.ProjectRead,
    Permission.ProjectWrite,
    Permission.ProjectMemberWrite,
    Permission.ProjectCreate,
    Permission.ProjectArchive,
    Permission.AssetRead,
    Permission.AssetWrite,
    Permission.AssetDelete,
    Permission.ExposureRead,
    Permission.ScopeRead,
    Permission.ScopeWrite,
    Permission.DiscoveryRead,
    Permission.DiscoveryRun,
    Permission.RiskRead,
    Permission.RiskWrite,
    Permission.RiskAccept,
    Permission.RiskSuppress,
    Permission.TicketRead,
    Permission.TicketWrite,
    Permission.TicketApprove,
    Permission.ReportRead,
    Permission.ReportExport,
    Permission.NotificationWrite,
    Permission.AuditRead
  ],
  project_owner: [
    Permission.ProjectRead,
    Permission.ProjectWrite,
    Permission.ProjectMemberWrite,
    Permission.AssetRead,
    Permission.AssetWrite,
    Permission.AssetDelete,
    Permission.ExposureRead,
    Permission.ScopeRead,
    Permission.ScopeWrite,
    Permission.DiscoveryRead,
    Permission.DiscoveryRun,
    Permission.RiskRead,
    Permission.RiskWrite,
    Permission.RiskAccept,
    Permission.TicketRead,
    Permission.TicketWrite,
    Permission.TicketApprove,
    Permission.ReportRead
  ],
  security_ops: [
    Permission.ProjectRead,
    Permission.AssetRead,
    Permission.AssetWrite,
    Permission.ExposureRead,
    Permission.ScopeRead,
    Permission.DiscoveryRead,
    Permission.DiscoveryRun,
    Permission.RiskRead,
    Permission.RiskWrite,
    Permission.TicketRead,
    Permission.TicketWrite,
    Permission.ReportRead
  ],
  developer: [
    Permission.ProjectRead,
    Permission.AssetRead,
    Permission.ExposureRead,
    Permission.DiscoveryRead,
    Permission.RiskRead,
    Permission.TicketRead,
    Permission.TicketWrite,
    Permission.ReportRead
  ],
  viewer: [
    Permission.ProjectRead,
    Permission.AssetRead,
    Permission.ExposureRead,
    Permission.DiscoveryRead,
    Permission.RiskRead,
    Permission.TicketRead,
    Permission.ReportRead
  ]
};

export function hasPermission(permissions: Permission[], permission: Permission) {
  return permissions.includes(permission);
}
